# Build settings
permalink: /:title/ # posts are symlinked from the ARC for the article feed
source: app
markdown: kramdown
keep_files:
    - dist
exclude:
    - assets

# Site settings
url: ""
baseurl: ""

title: "Tyler &amp; Co Auction Services"

destination: docs
